# Generated by Django 5.2.13 on 2026-04-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_uic', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=50)),
                ('county_code', models.IntegerField()),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Institutions.region')),
            ],
            options={
                'unique_together': {('county_name', 'region_code')},
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_name', models.CharField(max_length=50)),
                ('learner_upi', models.CharField(max_length=10)),
                ('learner_assessment_number', models.CharField(max_length=10)),
                ('school_uic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_county_name', models.CharField(max_length=50)),
                ('sub_county_code', models.IntegerField()),
                ('county_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Institutions.county')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='sub_county_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Institutions.sub_county'),
        ),
    ]
